services:
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD","redis-cli","ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - network1
  # db:
  #   image: postgres
  #   container_name: db
  #   restart: always
  #   environment:
  #     POSTGRES_DB: db
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U root -d db"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   networks:
  #     - network1

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    #image: shanks28/erp:latest
    container_name: app
    restart: always
    depends_on:
      - redis
     # - db
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .env:/.env
      - .env:/app/.env
    networks:
      - network1

networks:
  network1:
    name: erp_network1
    driver: bridge