spring.application.name=ERP
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
.......
# Database Configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/db
# spring.datasource.url=jdbc:postgresql://erp-dev-db.cnco2oq6ur26.ap-south-1.rds.amazonaws.com:5432/erp_db
#spring.datasource.username=root
#spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Configure Hibernate ORM
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Customize the OpenAPI documentation
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
#Configure Redis
# spring.redis.host=erp-redis-dev-edrgsb.serverless.aps1.cache.amazonaws.com
#spring.redis.host=localhost
#spring.redis.port=6379
#admin config
spring.application.admin.enabled=true
logging.level.org.springframework=WARN
logging.level.root=INFO
